language: java
jdk:
  - oraclejdk8

sudo: true

services:
  - postgresql

install: true

before_script:
  - psql -c 'create database xy_inc;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'root';" -U postgres

script:
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false