coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        enabled: yes
        target: 70%

    patch:
      default:
        enabled: yes
        target: 30%

comment:
  layout: "header, diff"
  behavior: default